/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  textbookSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // '.' means the sidebar will be generated from the docs folder structure
    },
  ],
};

module.exports = sidebars;