openapi: 3.0.0
info:
  title: Physical AI Robotics Textbook API
  description: API specification for the Physical AI Robotics textbook documentation site
  version: 1.0.0
  contact:
    name: Textbook Development Team
    email: textbook@example.com

servers:
  - url: https://physical-ai-robotics-book.github.io
    description: Production GitHub Pages deployment

paths:
  /:
    get:
      summary: Get the textbook homepage
      description: Returns the main landing page of the textbook
      responses:
        '200':
          description: Successful response with homepage content
          content:
            text/html:
              schema:
                type: string
                description: HTML content of the homepage

  /module-1:
    get:
      summary: Get Module 1 content
      description: Returns the content for Module 1 - The Robotic Nervous System (ROS 2)
      responses:
        '200':
          description: Successful response with Module 1 content
          content:
            text/html:
              schema:
                type: string
                description: HTML content of Module 1

  /module-2:
    get:
      summary: Get Module 2 content
      description: Returns the content for Module 2 - The Digital Twin (Gazebo & Unity)
      responses:
        '200':
          description: Successful response with Module 2 content
          content:
            text/html:
              schema:
                type: string
                description: HTML content of Module 2

  /module-3:
    get:
      summary: Get Module 3 content
      description: Returns the content for Module 3 - The AI-Robot Brain (NVIDIA Isaac)
      responses:
        '200':
          description: Successful response with Module 3 content
          content:
            text/html:
              schema:
                type: string
                description: HTML content of Module 3

  /module-4:
    get:
      summary: Get Module 4 content
      description: Returns the content for Module 4 - Vision-Language-Action (VLA)
      responses:
        '200':
          description: Successful response with Module 4 content
          content:
            text/html:
              schema:
                type: string
                description: HTML content of Module 4

  /search:
    get:
      summary: Search textbook content
      description: Search across all textbook modules and chapters
      parameters:
        - name: q
          in: query
          required: true
          description: Search query
          schema:
            type: string
        - name: limit
          in: query
          required: false
          description: Maximum number of results to return
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: Search results
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        title:
                          type: string
                          description: Title of the matching page
                        url:
                          type: string
                          description: URL of the matching page
                        excerpt:
                          type: string
                          description: Excerpt from the matching content

  /api/docs:
    get:
      summary: Get API documentation
      description: Returns the OpenAPI specification for the textbook API
      responses:
        '200':
          description: OpenAPI specification
          content:
            application/json:
              schema:
                type: object
                description: OpenAPI specification

components:
  schemas:
    Module:
      type: object
      required:
        - id
        - title
        - description
        - chapters
      properties:
        id:
          type: string
          description: Unique identifier for the module
        title:
          type: string
          description: Title of the module
        description:
          type: string
          description: Brief description of the module
        chapters:
          type: array
          items:
            $ref: '#/components/schemas/Chapter'
        learningObjectives:
          type: array
          items:
            type: string
          description: List of learning objectives for the module

    Chapter:
      type: object
      required:
        - id
        - title
        - content
      properties:
        id:
          type: string
          description: Unique identifier for the chapter
        title:
          type: string
          description: Title of the chapter
        content:
          type: string
          description: Chapter content in Markdown format
        learningObjectives:
          type: array
          items:
            type: string
          description: List of learning objectives for the chapter
        prerequisites:
          type: array
          items:
            type: string
          description: Prerequisites for this chapter
        toolsUsed:
          type: array
          items:
            type: string
          description: Tools and technologies used in this chapter

tags:
  - name: textbook
    description: Textbook content endpoints
  - name: search
    description: Search functionality
  - name: modules
    description: Individual module endpoints